model_name: MatRIS-v050-MPtrj
model_key: matris-v050-mptrj
model_version: v0.5.0
matbench_discovery_version: 1.3.1
date_added: "2025-03-13"
date_published: "2025-03-13"
authors:
  - name: Yuanchang Zhou
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: zhouyuanchang23s@ict.ac.cn
    orcid: https://orcid.org/0009-0004-6801-7033
  - name: Siyu Hu
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: husiyu@ict.ac.cn
    orcid: https://orcid.org/0009-0008-6085-4645
  - name: Chen Wang
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: wangchen246@mails.ucas.ac.cn
    orcid: https://orcid.org/0009-0006-7542-8281
  - name: Guangming Tan
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: tgm@ict.ac.cn
    orcid: https://orcid.org/0000-0002-6361-5948
  - name: Weile Jia
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: jiaweile@ict.ac.cn
    orcid: https://orcid.org/0000-0001-8539-8326
    corresponding: true
trained_by:
  - name: Yuanchang Zhou
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: zhouyuanchang23s@ict.ac.cn
    orcid: https://orcid.org/0009-0004-6801-7033

repo: https://github.com/HPC-AI-Team/MatRIS
url: https://github.com/HPC-AI-Team/MatRIS # to be released soon
doi: https://github.com/HPC-AI-Team/MatRIS # to be released soon
preprint: https://github.com/HPC-AI-Team/MatRIS # to be released soon

openness: OSOD
train_task: S2EFSM
test_task: IS2RE-SR
targets: EFS_GM
model_type: UIP
model_params: 5825620
trained_for_benchmark: true
n_estimators: 1

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: MAE
  loss_weights:
    energy: 5.0
    force: 5.0
    stress: 0.1
    magmom: 0.1
  batch_size: 160
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=300)
  epochs: 30
  n_layers: 6
  n_features: 128
  n_radial_bessel_basis: 7
  radial_cutoff: 6.0

requirements:
  torch: 2.4.1
  ase: 3.23.0
  pymatgen: 2024.11.23
  numpy: 1.26.4

training_set: [MPtrj]

notes: # notes can have any key, be multiline and support markdown.
  description: |
    MatRIS is a foundation model for materials representation and interaction simulation.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.861
      pred_file: models/matris/matris-0.5.0-mptrj/2025-03-12-kappa-103-fire-dist=0.01-fmax1e-4-symprec1e-5.json.gz
      pred_file_url: https://figshare.com/files/52962263
  geo_opt:
    pred_file: models/matris/matris-0.5.0-mptrj/2025-03-12-wbm-geo-opt.json.gz
    pred_file_url: https://figshare.com/files/52970030
    struct_col: matris_structure
    symprec=1e-5:
      rmsd: 0.0156 # Å
      n_sym_ops_mae: 5.7108 # unitless
      symmetry_decrease: 0.593 # fraction
      symmetry_match: 0.3362 # fraction
      symmetry_increase: 0.0619 # fraction
      n_structures: 256959 # count
      analysis_file: models/matris/matris-0.5.0-mptrj/2025-03-12-wbm-geo-opt-symprec=1e-5.csv.gz
      analysis_file_url: https://figshare.com/files/52969799
    symprec=1e-2:
      rmsd: 0.0156 # Å
      n_sym_ops_mae: 2.0591 # unitless
      symmetry_decrease: 0.0955 # fraction
      symmetry_match: 0.7874 # fraction
      symmetry_increase: 0.1091 # fraction
      n_structures: 256959 # count
      analysis_file: models/matris/matris-0.5.0-mptrj/2025-03-12-wbm-geo-opt-symprec=1e-2.csv.gz
      analysis_file_url: https://figshare.com/files/52969778
  discovery:
    pred_file: models/matris/matris-0.5.0-mptrj/2025-03-12-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/52969736
    pred_col: e_form_per_atom_matris_mp
